// react_lesson/react-router-juejin/src/pages/Home/Home.js
import { NavLink } from "react-router-dom"
import './home.css'
const Home = () => {
  return (
    <div className='home'>
      <div className="nav-list">
        <NavLink isActive={(match, location) => (location.pathname === '/' || location.pathname === '/recommended') ? true : false} to='/recommended'>推荐</NavLink>
        <NavLink to='/frontend'>前端</NavLink>
        <NavLink to='/backend'>后端</NavLink>
      </div>
    </div>
  );
}

export default Home;

// vue_lesson/vue-juejin/src/views/Home.vue
<template>
  <div>
    <ul>
      <li>
        <router-link to="/recommended">推荐</router-link>
      </li>
      <li>
        <router-link to="/frontend">前端</router-link>
      </li>
      <li>
        <router-link to="/backend">后端</router-link>
      </li>
    </ul>
    <!-- 文章列表,所有的文章列表布局和样式都一样只不过是数据发生了变化 -->
    <!-- 这种情况我们通常会用一个组件表示，根据不同的数据作展示 -->
    <router-view />
  </div>
</template>

<script>
export default {
  name: "Home"
};
</script>
