// vue_lesson/vue-todo/src/components/TodoFooter.vue
<template>
  <div>
    <span>{{activeNum}} {{activeNum === 1 ? 'item' : 'items'}} left</span>
    <button @click="$emit('change-type','all')" :class="type === 'all' ? 'color' : ''">all</button>
    <button @click="$emit('change-type','active')" :class="type === 'active' ? 'color' : ''">active</button>
    <button
      @click="$emit('change-type','completed')"
      :class="type === 'completed' ? 'color' : ''"
    >completed</button>
  </div>
</template>

<script>
export default {
  name: 'TodoFooter',
  props: ['activeNum', 'type']
}
</script>

<style>
.color {
  color: red;
}
</style>

// react_lesson/dva-demo/src/components/TodoFooter.js
const TodoFooter = ({ dispatch, filterType, activeNum }) => {
  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between' }}>
        <span>{activeNum} item{activeNum !== 1 && 's'} left</span>
        <div className="btns">
          <button style={{ color: filterType === 'all' && 'red' }} onClick={() => dispatch({ type: 'filterType/changeType', filterType: 'all' })}>all</button>
          <button style={{ color: filterType === 'active' && 'red' }} onClick={() => dispatch({ type: 'filterType/changeType', filterType: 'active' })}>active</button>
          <button style={{ color: filterType === 'completed' && 'red' }} onClick={() => dispatch({ type: 'filterType/changeType', filterType: 'completed' })}>completed</button>
        </div>
        <button onClick={() => dispatch({ type: 'todoList/clearCompletedTodo' })}>clear completed</button>
      </div>
    </div>
  );
}

export default TodoFooter;
