// vue_lesson/vue-todo/src/components/TodoFooter.vue
<template>
  <div>
    <span>{{activeNum}} {{activeNum === 1 ? 'item' : 'items'}} left</span>
    <button @click="$emit('change-type','all')" :class="type === 'all' ? 'color' : ''">all</button>
    <button @click="$emit('change-type','active')" :class="type === 'active' ? 'color' : ''">active</button>
    <button
      @click="$emit('change-type','completed')"
      :class="type === 'completed' ? 'color' : ''"
    >completed</button>
  </div>
</template>

<script>
export default {
  name: 'TodoFooter',
  props: ['activeNum', 'type']
}
</script>

<style>
.color {
  color: red;
}
</style>

// react_lesson/react-todo/src/components/TodoFooter/TodoFooter.js
import './todo-footer.css'
const TodoFooter = ({ filterType, changeFilterType, activeTodosNum, deleteAllCompletedTodo, completedTodosNum }) => {
  return (
    <div className="todo-footer">
      <div className="left">
        <span>{activeTodosNum} item{activeTodosNum !== 1 && 's'} left</span>
      </div>
      <div className="mid">
        <button onClick={() => { changeFilterType('all') }} style={{ color: filterType === 'all' ? 'red' : '#000' }}>all</button>
        <button onClick={() => { changeFilterType('active') }} style={{ color: filterType === 'active' ? 'red' : '#000' }}>active</button>
        <button onClick={() => { changeFilterType('completed') }} style={{ color: filterType === 'completed' ? 'red' : '#000' }}>completed</button>
      </div>

      <div style={{width: '80px'}} className='right'>
        {completedTodosNum > 0 && <button onClick={deleteAllCompletedTodo}>completed</button>}
      </div>
    </div>
  );
}

export default TodoFooter;
